### PR TITLE
Updates for Ubuntu 16.04, Chef 13, triggering fewer restart notifications, configuring the java heap size

### PR DESCRIPTION
**Pull request by RoboticCheese**
This template, as used in the [sumologic_collector provider](https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/providers/default.rb#L47),
triggers a restart notification. The presence of a timestamp means the file
content changes and a new restart notification is sent for every Chef run.

### CODE REVIEW

**Comment by RoboticCheese** [comment]
Ended up with a few more commits in the process of getting a Sumo deployment onto Ubuntu 16.04. Can remove any that are disapproved of and/or split into separate PRs as needed.

**Comment by zl4bv** [comment]
Once the conflict has been resolved I'll be happy to merge.

**Comment by RoboticCheese** [comment]
Did a rebase to fix the merge conflict and added the last commit with a (not great, but functional) solution for a couple issues around when the collector is being started up for the first time and registering.

**Comment by RoboticCheese** [comment]
Most of the style offenses in the failed build are unrelated to this change. Will look at resolving the one that is related and any others that wouldn't require too much refactoring to do.

**Comment by RoboticCheese** [comment]
Refactored the large ruby_block resource that introduced a new FoodCritic failure into a set of helper methods.

**Comment by potato20** [comment]
At the moment when I'm using `sumo_source_syslog`, I get

`file[/etc/sumo.json/syslog.json] (/var/chef/cache/cookbooks/sumologic-collector/libraries/provider_source.rb line 21) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/sumo.json does not exist.`

so i guess it needs to be created [here](https://github.com/RoboticCheese/sumologic-collector-chef-cookbook/blob/jdh-time-in-a-template/libraries/provider_source.rb#L21)

**Comment by potato20** [comment]
Specifically

```
sumo_source_syslog 'syslog' do
  source_json_directory node['sumologic']['sumo_json_path']
end
```

**Comment by luckytaxi** [comment]
Is there an update to this? I'm running into issue #131

**Comment by RoboticCheese** [comment]
Rebased after the most recent updates for RuboCop and the build passes now, wooooo!

**Comment by RoboticCheese** [comment]
Oops, my bad. Originally wrote this on Windows and just noticed a bunch of carriage returns that snuck into the modified template file. That's fixed now.

**Comment by majormoses** [comment]
@duchatran lets cut a release on this.

**Pull request merged**
