### PR TITLE
Adds the ability to change the default category in the files added to the sumo sources folder.

### PR DESCRIPTION
**Pull request by aquantumofdata**
Adds the ability to manage the categories in the default files added to the sources folder when using the new local source mechanism.

This will allow orgs to manage where the syslog files for there orgs are categorised too.

### CODE REVIEW

**Comment by aquantumofdata** [comment]
Tested against local recipe

**Comment by duchatran** [comment]
@aquantumofdata : could you update the CHANGE Log too?

**Comment by aquantumofdata** [comment]
Done

**Comment by duchatran** [comment]
Thanks @aquantumofdata!

**Pull request merged**
