### PR TITLE
Make installation more customisable and idempotent

### PR DESCRIPTION
**Pull request by zl4bv**
As per the title, the goal of this PR is to give the cookbook user more choice about how they install the collector and make the general installation process more idempotent.

Key changes:
* Separate the platform-specific installation methods into separate recipes so the user can explicitly choose an install method by including a specific recipe in their run list if they don't want to rely on the platform guesswork in `recipes/install.rb`
* Add a LWRP that allows the cookbook user to run the collector's install script and supply any/all of the supported options. Under the hood it will check if the collector is already installed, so running the resource when the collector is already installed will result in Chef not trying to install the collector again. The use case for the resource is to allow a user to declare this resource in a third party cookbook (e.g. internal company cookbook) instead of adding the `install` recipe to their run list and have complete control of their collector installation process.

Although these changes mean a bunch of attributes and code in the recipes could be cleaned up, I've left them there to avoid compatibility issues for existing users of this cookbook.

I ran the integration tests locally but with tweaks to the `.kitchen.yml` because the current settings seem to match some workflow internal to Sumo Logic. It would be nice to see the tests running in a public CI system too, such as Travis, so it is easier to collaboratively review PRs.

### CODE REVIEW

**Comment by jcadarsh** [comment]
Two people working on different floors working on exactly the same thing :-)

**Comment by zl4bv** [comment]
Looks like I need to rebase this PR. I'll try to get this done in the next couple of days.

**Comment by sumoway** [comment]
@zl4bv this is really great.  I'm ready to merge and test locally.  I will wait for your rebase (I would attempt the rebase myself but I just learned what that is and I'm afraid the implications are over my head at the moment).

**Comment by Z3r0Sum** [comment]
@zl4bv nice job! I missed the fact you included windows within this...  Could we be a bit more scientific about determining whether sumo is installed?  Doing it just by directory seems bad.  I used service in my PR.  Maybe both?  Not sure, but I think just directory is a bit weak.

**Comment by duchatran** [comment]
@zl4bv or @jcadarsh (also @Z3r0Sum): I resolved this PR with latest master at branch: 
https://github.com/SumoLogic/sumologic-collector-chef-cookbook/tree/zl4bv-idempotence
Can you guys check if this branch cover all your cases before I merge it back to master?

**Comment by zl4bv** [comment]
Thanks @duchatran and sorry I didn't get around to rebasing the changes myself sooner. 

One thing that is missing from the rebase is @Z3r0Sum's point regarding the detection of an existing install of the collector. Do we want to change it to check for the presence of the collector service rather than relying on the existence of a directory?

Also, do the tests still pass? ;)

**Comment by Z3r0Sum** [comment]
One other point I'll add is the following:

On windows, might be true for Linux as well, if the install fails the directory will still reside there; thus, preventing Chef from correcting this on the next run.  We had an issue with an old API Key for sumo that caused the install to fail, but the current way the cookbook was handling it did not account for this edge case.

**Comment by sumoway** [comment]
@Z3r0Sum good point.  I've seen a similar situation on Linux.  The challenge is definition of "installed" in the context of a Sumo Logic collector.  You can have everything in place (/opt/SumoCollector/* and /etc/init.d/collector) which might meet a standard definition of "installed", but the collector is useless until it's _registered_.  There is another key generated after registration.  We may want to look for that.

**Pull request merged**
