### PR TITLE
sumologic_collector resource

### PR DESCRIPTION
**Pull request by KierranM**
## sumologic_collector
This PR creates a new `sumologic_collector` resource to treat the collector like a service. Allowing it to be easily installed, configured, removed, and controlled by chef.

The actions on the new resource are:

#### :install_and_configure (default action)
This action does the same thing as the current `sumologic_collector_installer` resource does.
I have kept the existing sumologic_collector_installer resource for backwards compatibility (to be removed later), it is now just a shim for the new resource.

#### :install
Installs the sumologic collector without configuration and without registering it as a collector
The intention behind this is to be used to just install the the collector with no configuration so that it can be configured (likely by Chef) at a later time. This allows separation of installation and configuration to make processes like baking collectors into AMI's easier.

#### :configure
Pairs with the `:install` action, this action configures an installed Collector.
Ideally the collector that is being configured won't have been registered yet as some of these settings only work on first registration. A use case for this is AMI baking, the collector can be baked into an AMI with the `:install` action, and then configured on instance launch using the `:configure` action.

#### :remove
Uninstalls an installed collector using the provided uninstaller

#### :start, :stop, :restart
These service methods do exactly what they say, performing the defined action against the collector

### CODE REVIEW

**Comment by duchatran** [comment]
@KierranM: Thanks for the PR. Do you expect to include more for this PR?

**Comment by KierranM** [comment]
Not into this PR, unless you can see anything that could be improved

**Comment by KierranM** [comment]
@duchatran, when you merge this would you kindly bump the version and release to the supermarket as soon as it suits you. I'd like to use these changes without referring to my fork. Thanks.

**Comment by meringu** [comment]
:+1: :shipit:

**Comment by zl4bv** [comment]
Cool!

**Comment by duchatran** [comment]
Done, also posted to supermarket

**Pull request merged**
