### PR TITLE
Add support for additional resource-configured collector attributes

### PR DESCRIPTION
**Pull request by RoboticCheese**
## Pull Request Checklist

**Is this in reference to an existing issue?**

N/A

#### General

- [x] Remove any versioning you did yourself if applicable

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/) with all new changes under `## [Unreleased]` and using a `### Added, Fixed, Changed, or Breaking Change` sub-header.

- [x] Update README with any necessary changes

- [x] RuboCop passes

- [x] Foodcritic passes

- [ ] Existing tests pass

\* I should note that the `default-resource-configure-*` Kitchen suite is failing, but predating and unrelated to this change.

#### Purpose

Most of these were added relatively recently, with v19.182. In particular, we found the ability to set a collector-wide default hostname and time zone especially appealing.

#### Known Compatibility Issues

N/A

### CODE REVIEW

**Comment by RoboticCheese** [comment]
Done.

Except for `disable_action_source` and `disable_upgrade` defaulting to `false` to match `disable_script_source`.

**Comment by majormoses** [comment]
@duchatran ping for release

**Comment by acranox** [comment]
The release notes make it look like the `disable_upgrade` option was included in release v.1.2.23, but looking through the code, I think those changes weren't actually included in the release, and as still sitting in the unreleased master branch.
Can we get these changes into the next release?  And get the Changelog updated to accurately reflect the features?

**Comment by majormoses** [comment]
validated, ping @duchatran for fixup on changelog and release.

**Comment by majormoses** [comment]
Diff Link: https://github.com/SumoLogic/sumologic-collector-chef-cookbook/compare/v1.2.23...HEAD

**Pull request merged**
