### PR TITLE
add max_memory attribute to allow configuration of the memory consump…

### PR DESCRIPTION
**Pull request by dannenberg**
…tion of the collector

### CODE REVIEW

**Comment by dannenberg** [comment]
@duchatran This change is much simpler than my last and I believe it is much safer as well.

**Comment by dannenberg** [comment]
Your linter is blowing up, but not on any lines I touched... not sure what I should do about that.

**Comment by majormoses** [comment]
@dannenberg after seeing those errors I created #130 to fix all those rubocop issues...

**Comment by dannenberg** [comment]
@majormoses sweet. I'll rebase once yours is merged.

**Comment by dannenberg** [comment]
pinging @frankreno due to a conversation earlier today

**Comment by dannenberg** [comment]
@majormoses i rebased but i'm still seeing a lot of unrelated linter errors still

**Comment by majormoses** [comment]
ya I just had a discussion with some internal sumo folks after spending some time looking at their test suite (feel free to join in there). https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/133#issuecomment-307936881

**Comment by majormoses** [comment]
@dannenberg I was made a collaborator today and I am fixing up all these CI issues... once this lands #134  you can rebase off master and it should be much more stable. I will start adding real testing as well not just linting...

**Comment by majormoses** [comment]
@dannenberg I rebased for you.

**Comment by dannenberg** [comment]
thanks!

**Pull request merged**
